# Nome da aplica\u00e7\u00e3o
spring.application.name=prg03spring

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# URL de conex\u00e3o com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Usu\u00e1rio do banco
spring.datasource.username=postgres

# Senha do banco
spring.datasource.password=root

# Atualiza automaticamente as tabelas
spring.jpa.hibernate.ddl-auto=update

# Exibe os comandos SQL no console
spring.jpa.show-sql=true

# Formata os comandos SQL
spring.jpa.properties.hibernate.format_sql=true