/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.table.DefaultTableModel;
import javax.swing.JCheckBox;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import jakarta.annotation.PostConstruct;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author anriu
 */

@Component
public class CursoListar extends javax.swing.JFrame {

    /**
     * Creates new form CursoListar
     */
    
    private TableRowSorter<DefaultTableModel> sorter;
            
    
    @Autowired
    private CursoIController cursoController;
    @Autowired
    private ApplicationContext context;
    
    public CursoListar() {
        
        initComponents();

        setSize(900, 737);
        setResizable(false);
        setLocationRelativeTo(null);
    
        tblDados.setRowHeight(35);
       
        
        tblDados.getColumnModel().getColumn(0).setMaxWidth(70);
        tblDados.getColumnModel().getColumn(0).setMinWidth(70);
        
        tblDados.getColumnModel().getColumn(3).setMaxWidth(80);
        tblDados.getColumnModel().getColumn(3).setMinWidth(80);

        tblDados.getColumnModel().getColumn(4).setMaxWidth(80);
        tblDados.getColumnModel().getColumn(4).setMinWidth(80);
        
        
        DefaultTableModel model = (DefaultTableModel) tblDados.getModel();

        sorter = new TableRowSorter<>(model);
        tblDados.setRowSorter(sorter);

        txtPesquisar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filtrar();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filtrar();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filtrar();
        }
        });
        
        
    }

    @PostConstruct
    public void iniciarBotoesTabela() {

        // Coluna remover
        tblDados.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());

        tblDados.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JCheckBox(), cursoController));

        // Coluna editar
        tblDados.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());

        tblDados.getColumnModel().getColumn(4).setCellEditor(new ButtonEditor(new JCheckBox(), cursoController));
    }
    
    
    @jakarta.annotation.PostConstruct
    public void iniciarTela() {
        listarCursos();
    }
    
    public void listarCursos() {

        // Pega o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) tblDados.getModel();

        // Cria o controller responsável pelas operações do curso
       

        // Limpa todas as linhas da tabela
        model.setRowCount(0);

        // Busca todos os cursos cadastrados
        List<Curso> listaCursos = cursoController.findAll();

        // Percorre a lista de cursos
        for (Curso curso : listaCursos) {

        // Adiciona os dados do curso na tabela
        model.addRow(new Object[]{
            curso.getId(),
            curso.getNome(),
            curso.getCodigoCurso()
        });
    }
}
    
    private void filtrar() {
        // Pega o texto digitado no campo de pesquisa
        String texto = txtPesquisar.getText();

        if (texto.trim().isEmpty()) {
            // Remove o filtro e exibe todos os dados
            sorter.setRowFilter(null);
        } else {
            // Filtra os dados da tabela ignorando letras maiúsculas/minúsculas
            // A coluna 1 representa a coluna "Nome"
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 1));
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        bntAdicionar = new javax.swing.JButton();
        bntAtualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroud.setBackground(new java.awt.Color(20, 41, 58));
        backgroud.setPreferredSize(new java.awt.Dimension(900, 700));

        tblDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CODIGO", "REMOVER", "EDITAR"
            }
        ));
        tblDados.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDadosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblDados);

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        bntAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntAdicionar.setText("ADICIONAR CURSO");
        bntAdicionar.setAlignmentY(0.0F);
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        bntAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntAtualizar.setText("Atualizar lista");
        bntAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CURSOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PESQUISA POR NOME:");

        javax.swing.GroupLayout backgroudLayout = new javax.swing.GroupLayout(backgroud);
        backgroud.setLayout(backgroudLayout);
        backgroudLayout.setHorizontalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(401, 401, 401))
            .addGroup(backgroudLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(bntAtualizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroudLayout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(bntAdicionar)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        backgroudLayout.setVerticalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroudLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisar))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(bntAtualizar)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDadosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDadosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDadosAncestorAdded

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
        // TODO add your handling code here:
         DadosCurso dadosCursos = context.getBean(DadosCurso.class);

        dadosCursos.setVisible(true);

        listarCursos();
    }//GEN-LAST:event_bntAdicionarActionPerformed

    private void bntAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtualizarActionPerformed
        // TODO add your handling code here:
        listarCursos();
    }//GEN-LAST:event_bntAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroud;
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
